import { Command } from "https://raw.githubusercontent.com/brettkolodny/slash-server/main/mod.ts";

if (!Deno.env.get("SERVER_ID")) throw Error("Environment variables not set");

const SERVER_ID = Deno.env.get("SERVER_ID")!;

const acalaRelease = new Command();
acalaRelease.name = "acala-release";
acalaRelease.description = "When will Acala go live?";
acalaRelease.response = `
Acala will go live after winning a [Polkadot Parachain Slot](1).
[ACA](https://acala.network/acala/token) tokens will be distributed after the parachain slot has been won. 
Sadly we don't know the date or timeframe on this, because it's in the hands of Polkadot to provide us and the community with a date. But it should be in the near future. 
`;
acalaRelease.serverId = SERVER_ID;

const karAcalaStaking = new Command();
karAcalaStaking.name = "aca-kar-staking";
karAcalaStaking.description =
  "Can I directly stake my KAR/ACA Token in the future?";
karAcalaStaking.response = `
Most likely not. 
[KAR](https://acala.network/karura/token) and [ACA](https://acala.network/acala/token) token supplies are fixed and deflationary.
There are no planned or active staking mechanisms. 
However liquidity may be deposited into supported LPs for additional yield over HODLing plus [potential Incentives](https://wiki.karura.app/earn). 
`;
karAcalaStaking.serverId = SERVER_ID;

const kusdPrice = new Command();
kusdPrice.name = "kusd-price";
kusdPrice.description = "Why is the kUSD price fluctuating?";
kusdPrice.response =
  "The [kUSD](https://wiki.acala.network/karura/defi-hub/kusd-stablecoin/protocol-overview) is designed to be pegged to the US Dollar at a 1:1 ratio through automatic risk management mechanisms and on-chain governance. [kUSD](https://wiki.acala.network/karura/defi-hub/kusd-stablecoin/protocol-overview) fluctuates depending on supply and demand. The more [kUSD](https://wiki.acala.network/karura/defi-hub/kusd-stablecoin/protocol-overview) is used the more collateral it is backed by, which in turn will make it more stable.";
kusdPrice.serverId = SERVER_ID;

const tokenUseCases = new Command();
tokenUseCases.name = "usecases";
tokenUseCases.description = "Which tokens will get listed next on Karura?";
tokenUseCases.response =
  "All tokens must go through [governance](https://wiki.acala.network/karura/get-started/governance) approval before being listed. Please stay up to date with current proposals in our [forum](https://acala.discourse.group/), also please see the official [Karura roadmap](https://www.notion.so/dcabf9ba7c6246c69b913d5972503227?v=4121894373fd43d98ffcac260803928d).";
tokenUseCases.serverId = SERVER_ID;

const lksm = new Command();
lksm.name = "lksm";
lksm.description =
  "How does LKSM work and how do I see my staking rewards on my KSM?";
lksm.response = `
[LKSM](https://wiki.acala.network/karura/defi-hub/liquid-staking/lksm) represents the accrual of yield generated by your staked KSM. You can find your staking rewards in your portfolio (w/wallet symbol) at the top left of the Karura app. 
More detailed information about [LKSM](https://wiki.acala.network/karura/defi-hub/liquid-staking/lksm) is provided in our [Wiki.](https://wiki.karura.app/liquid-staking)
`;
lksm.serverId = SERVER_ID;

const karuraListings = new Command();
karuraListings.name = "karura-listings";
karuraListings.description = "Which tokens will get listed next on Karura?";
karuraListings.response =
  "All tokens must go through [governance](https://wiki.acala.network/karura/get-started/governance) approval before being listed. Please stay up to date with current proposals in our [forum](https://acala.discourse.group/), also please see the official [Karura roadmap](https://www.notion.so/dcabf9ba7c6246c69b913d5972503227?v=4121894373fd43d98ffcac260803928d).";
karuraListings.serverId = SERVER_ID;

const karuraFuture = new Command();
karuraFuture.name = "karura-future";
karuraFuture.description =
  "What will happen with Karura after Acalas’s Launch and will Karura be connected to Acala somehow?";
karuraFuture.response =
  "As a canary network of [Acala](https://acala.network/acala/), [Karura](https://acala.network/karura/) serves as a proving ground, for network participants and developers to build on and try out [Acala](https://acala.network/acala/)'s governance, stablecoin monetary policies, staking derivatives etc. with real economic incentives. Having gone live first, [Karura](https://acala.network/karura/) is also governed by its own community and as such will proceed further, independently to some extent, based upon the wants and needs of its users + suggestions/mandatory improvements & upgrades implemented by the team until such time as total democratic decentralization has occurred.";
karuraFuture.serverId = SERVER_ID;

const ledger = new Command();
ledger.name = "ledger";
ledger.description = "Can I use my Ledger for my KAR/ACA Tokens?";
ledger.response =
  "Neither [KAR](https://acala.network/karura/token) nor [ACA](https://acala.network/acala/token) are currently supported by Ledger.";
ledger.serverId = SERVER_ID;

const lp = new Command();
lp.name = "lp";
lp.description = "How can I find information about Karuras Liquidity Pools, what are the incentives to be a Liquidity Provider, and what are the risks?";
lp.response = `
Statistics and more on Karura LPs + TVL can be found at our [Karura Stat Dashboard.](https://stats.karura.network/)
All the information regarding incentives, risks and more **can be found in our** [Wiki.](https://wiki.karura.app/earn)
`;
lp.serverId = SERVER_ID;

export default [
  acalaRelease,
  karAcalaStaking,
  kusdPrice,
  tokenUseCases,
  lksm,
  karuraListings,
  ledger,
  karuraFuture,
  lp,
];
