const generalFAQ = `
# Top 10 Community Questions (Discord Slashes)

## acala-release
### When will Acala go live 
Acala will go live after winning a [Polkadot Parachain Slot](1).
[ACA](https://acala.network/acala/token) tokens will be distributed after the parachain slot has been won. 
Sadly we don't know the date or timeframe on this, because it's in the hands of Polkadot to provide us and the community with a date. But it should be in the near future. 


## aca-kar-staking
### Can I directly stake my KAR/ACA Token in the future?
Most likely not. 
[KAR](https://acala.network/karura/token) and [ACA](https://acala.network/acala/token) token supplies are fixed and deflationary.
There are no planned or active staking mechanisms. 
However liquidity may be deposited into supported LPs for additional yield over HODLing plus [potential Incentives](https://wiki.karura.app/earn).  


## kusd-price
### Why is the kUSD price fluctuating?
The [kUSD](https://wiki.acala.network/karura/defi-hub/kusd-stablecoin/protocol-overview) is designed to be pegged to the US Dollar at a 1:1 ratio through automatic risk management mechanisms and on-chain governance. [kUSD](https://wiki.acala.network/karura/defi-hub/kusd-stablecoin/protocol-overview) fluctuates depending on supply and demand. The more [kUSD](https://wiki.acala.network/karura/defi-hub/kusd-stablecoin/protocol-overview) is used the more collateral it is backed by, which in turn will make it more stable.


## usecases
### What are the use-cases for the KAR- and ACA-Token?
[ACA](https://acala.network/acala/token) + [KAR](https://acala.network/karura/token) will be/are used for [Governance](https://wiki.acala.network/karura/get-started/governance), Proof of liveness via parachain staking, paying [transaction fees](https://wiki.acala.network/karura/get-started/transaction-fees), Capital Reserve backing the stablecoin protocol in order to retain solvency in the event of [liquidation(s)](https://wiki.karura.app/mint-kusd/mint-kusd-faq#liquidation), and investment in the decentralized [Sovereign Wealth Fund (dsWF)](https://wiki.karura.app/mint-kusd/mint-kusd-faq#liquidation) for long term sustainability of the Network(s) and of course, [LPing](https://wiki.karura.app/earn) which may or may not include [incentives](https://wiki.karura.app/earn).

## karura-listings
### Which tokens will get listed next on Karura?
All tokens must go through [governance](https://wiki.acala.network/karura/get-started/governance) approval before being listed. Please stay up to date with current proposals in our [forum](https://acala.discourse.group/), also please see the official [Karura roadmap](https://www.notion.so/dcabf9ba7c6246c69b913d5972503227?v=4121894373fd43d98ffcac260803928d). 


## lksm
### How does LKSM work and how do I see my staking rewards on my KSM?
[LKSM](https://wiki.acala.network/karura/defi-hub/liquid-staking/lksm) represents the accrual of yield generated by your staked KSM. You can find your staking rewards in your portfolio (w/wallet symbol) at the top left of the Karura app. 
More detailed information about [LKSM](https://wiki.acala.network/karura/defi-hub/liquid-staking/lksm) is provided in our [Wiki.](https://wiki.karura.app/liquid-staking)


## karura-future
### What will happen with Karura after Acalas’s Launch and will Karura be connected to Acala somehow?
As a canary network of [Acala](https://acala.network/acala/), [Karura](https://acala.network/karura/) serves as a proving ground, for network participants and developers to build on and try out [Acala](https://acala.network/acala/)'s governance, stablecoin monetary policies, staking derivatives etc. with real economic incentives. Having gone live first, [Karura](https://acala.network/karura/) is also governed by its own community and as such will proceed further, independently to some extent, based upon the wants and needs of its users + suggestions/mandatory improvements & upgrades implemented by the team until such time as total democratic decentralization has occurred.

## ledger
### Can I use my Ledger for my KAR/ACA Tokens?
Neither [KAR](https://acala.network/karura/token) nor [ACA](https://acala.network/acala/token) are currently supported by Ledger.


## lp
### How can I find information the incentives, and risks of Karuras Liquidity Pools?
Statistics and more on Karura LPs + TVL can be found at our [Karura Stat Dashboard.](https://stats.karura.network/)
All the information regarding incentives, risks and more **can be found in our** [Wiki.](https://wiki.karura.app/earn)
`;

export default generalFAQ;